#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides:          watchdog-example
# Required-Start:    $local_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Watchdog for the example service
# Description:       Watchdog for the example service
### END INIT INFO

set -e

NAME="watchdog-example"

start() {
  if (($(ps -edf | grep /home/admin/repos/watchdog/watchdog.sh | grep example | wc -l) > 0))
  then
    echo 'Service is already running' && false
  else
    echo 'Starting service...'
    sudo -H -u admin /home/admin/repos/watchdog/watchdog.sh example >/dev/null &
    echo 'Service started' >&2
  fi
}

stop() {
  if (($(ps -edf | grep /home/admin/repos/watchdog/watchdog.sh | grep example | wc -l) > 0))
  then
    echo 'Stopping service...'
    ps -edf | grep /home/admin/repos/watchdog/watchdog.sh | grep example | awk '{print $2}' | xargs kill
    echo 'Service stopped' >&2
  else
    echo 'Service not running' >&2
    return 1
  fi
}

status() {
  if (($(ps -edf | grep /home/admin/repos/watchdog/watchdog.sh | grep example | wc -l) > 0))
  then
    echo "Service is running" && true
  else
    echo "Service is not running" && false
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|status}"
esac
